

services:
  train:
    build: .
    volumes:
      - .:/app
    command: python train.py --timesteps 200000 --reward_type shaped --save_path models/ppo_model.zip

  evaluate:
    build: .
    environment:
      - DISPLAY=${DISPLAY:-:0}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/app
    command: python evaluate.py --model_path models/ppo_model.zip